USE intern_app;
CREATE TABLE User(email CHAR(100) NOT NULL PRIMARY KEY, firstname CHAR(50) NOT NULL, lastname CHAR(50) NOT NULL, isAdmin BOOLEAN NOT NULL);
CREATE TABLE Event(eventID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title CHAR(50) NOT NULL, description CHAR(200) NOT NULL, location CHAR(100) NOT NULL, startTime DATE NOT NULL, endTime DATE NOT NULL);
CREATE TABLE Question(questionID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title CHAR(100) NOT NULL, description CHAR(200) NOT NULL, date DATE NOT NULL, email CHAR(100) NOT NULL, FOREIGN KEY (email) REFERENCES User(email));
CREATE TABLE Answer(answerID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, answer CHAR(200) NOT NULL, questionID INT UNSIGNED NOT NULL , email CHAR(100) NOT NULL, isVerified BOOLEAN NOT NULL, date DATE NOT NULL, FOREIGN KEY (questionID) REFERENCES Question(questionID), FOREIGN KEY (email) REFERENCES User(email));
